export const SET_AUTHENTIFICATION = 'SET_AUTHENTIFICATION'
export const GET_ACCOUNTS = 'GET_ACCOUNTS'
export const USER_INFO = 'USER_INFO'
export const GET_FILENAME = "GET_FILENAME"
export const GET_URL = "GET_URL"