export const SET_AUTHENTIFICATION = 'SET_AUTHENTIFICATION'
export const GET_ACCOUNTS = 'GET_ACCOUNTS'
export const USER_INFO = 'USER_INFO'
export const CATALOG_LIST = "CATALOG_LIST"
export const ADD_SOUND = "ADD_SOUND"