const Instruments = [
    {value:'Undefined', label:'Undefined'},
    {value:'Accordion', label:'Accordion'},
    {value:'Bagpipes', label:'Bagpipes'},
    {value:'Banjo', label:'Banjo'},
    {value:'Bassoon', label:'Bassoon'},
    {value:'Cello', label:'Cello'},
    {value:'Clarinet', label:'Clarinet'},
    {value:'Cymbal', label:'Cymbal'},
    {value:'Double bass', label:'Double bass'},
    {value:'Drum', label:'Drum'},
    {value:'Bass drum', label:'Bass drum'},
    {value:'Bongo drum', label:'Bongo drum'},
    {value:'Snare drum', label:'Snare drum'},
    {value:'Timpani', label:'Timpani'},
    {value:'Dulcimer', label:'Dulcimer'},
    {value:'Flute', label:'Flute'},
    {value:'French horn', label:'French horn'},
    {value:'Gong', label:'Gong'},
    {value:'Guitar', label:'Guitar'},
    {value:'Electric guitar', label:'Electric guitar'},
    {value:'Harp', label:'Harp'},
    {value:'Harpsichord', label:'Harpsichord'},
    {value:'Hurdy gurdy', label:'Hurdy gurdy'},
    {value:'Jew s harp', label:'Jew s harp'},
    {value:'Lute', label:'Lute'},
    {value:'Lyre', label:'Lyre'},
    {value:'Marimba', label:'Marimba'},
    {value:'Organ', label:'Organ'},
    {value:'Pan pipes', label:'Pan pipes'},
    {value:'Pennywhistle', label:'Pennywhistle'},
    {value:'Piano', label:'Piano'},
    {value:'Recorder', label:'Recorder'},
    {value:'Saxophone', label:'Saxophone'},
    {value:'Sitar', label:'Sitar'},
    {value:'Synthesizer', label:'Synthesizer'},
    {value:'Tambourine', label:'Tambourine'},
    {value:'Triangle', label:'Triangle'},
    {value:'Trombone', label:'Trombone'},
    {value:'Trumpet', label:'Trumpet'},
    {value:'Tuba', label:'Tuba'},
    {value:'Viola', label:'Viola'},
    {value:'Violin', label:'Violin'},
    {value:'Fiddle', label:'Fiddle'},
    {value:'Xylophone', label:'Xylophone'},
    {value:'Taikos', label:'Taikos'},
    {value:'Toms', label:'Toms'},
    {value:'Choir', label:'Choir'},
    {value:'Electric bass', label:'Electric bass'},
    {value:'Mandoline', label:'Mandoline'},
    {value:'HitHat', label:'HitHat'},
    {value:'Fx', label:'Fx'},
]

export default Instruments